{% set name = "jwcrypto" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 771a87762a0c081ae6166958a954f80848820b2ab066937dc8b8379d65b1b039

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cryptography >=3.4
    - typing_extensions

test:
  imports:
    - jwcrypto
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://jwcrypto.readthedocs.io/en/latest/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Implements JWK,JWS,JWE specifications using python-cryptography
  description: |
    An implementation of the JOSE Working Group documents: RFC 7515 - JSON Web
    Signature (JWS) RFC 7516 - JSON Web Encryption (JWE) RFC 7517 - JSON Web
    Key (JWK) RFC 7518 - JSON Web Algorithms (JWA) RFC 7519 - JSON Web Token
    (JWT) RFC 7520 - Examples of Protecting Content Using JSON Object Signing
    and Encryption (JOSE)
  doc_url: https://jwcrypto.readthedocs.io/en/latest/
  dev_url: https://github.com/latchset/jwcrypto

extra:
  recipe-maintainers:
    - aymondebroglie
    - scopatz
    - jan-janssen
